### ISSUE TITLE
`spawn ENAMETOOLONG` when trying to process too many files or files with long pathes

### ISSUE THREAD

**Issue by interpaul** [dbushell/grunt-svg2png#17]
I've got an error `Fatal error: spawn ENAMETOOLONG` when was tying to process too many files or files has too long pathes. 

My config:
```coffee
		svg2png:
			icons:
				files: [
					expand: false,
					cwd: 'src/files/icons/svg/',
					src: ['*.svg'],
					dest: 'src/files/icons/png/',
				]
```

![svg2png-error](https://cloud.githubusercontent.com/assets/475929/3882874/5e9524d6-219b-11e4-8179-3874943c29ee.gif)

Could you investigate please?

**Comment by MatmaRex** [comment]
I have also hit this, in a project with 293 files.

The problem is that this tool passes the list of files (as a JSON blobl) to phantomjs as a command-line parameter, and clearly when you have more than a couple thousand characters the thing blows up.

Instead, we can pass it via a pipe to the standard input. I have a patch for this, submitting a pull request shortly.
